### ISSUE TITLE
Do a create post page [FRONT-END]

### ISSUE THREAD

**Issue by Primeputin** [Primeputin/cornhub#2]
Make sure to make a different branch for this. Once the user clicks the + sign, the website will go to a page that has a form needed to filled to create a post. The page should still have the navigation bar on top. Leave the part for uploading the photo for later.  The theme of the page should be same with the rest of the pages of the website.

- [x] title
- [x] tags
- [x] description
- [x] submit button

**This should be done by February 11**

**Comment by Primeputin** [comment]
The tags you could use almost the same implementation from @LarsBasura if he is done with the edit post part

**Comment by nimbus7462** [comment]
for this should we create a different page after the submit button is pressed for the form?

**Comment by Primeputin** [comment]
> for this should we create a different page after the submit button is pressed for the form?

yeah sure it should go to home page

use the useNavigate() hook from react-router-dom library to do it
you have to import like this import { useNavigate } from 'react-router-dom';
then  declare it like this const navigate = useNavigate();
for like the button, you do onClick(()=>{useNavigate('/Home')})l
